using System;

namespace NAnt.DotNet.Types {
    /// <summary>
    /// Specifies the type of debugging information generated by the compiler.
    /// </summary>
    /// <remarks>
    ///   <para>
    ///   When set to either <see langword="true" />, <see cref="Full" /> or
    ///   <see cref="PdbOnly" /> then the following conditional compilation
    ///   symbols will also be defined:
    ///   </para>
    ///   <list type="bullet">
    ///     <item>
    ///       <description>DEBUG</description>
    ///     </item>
    ///     <item>
    ///       <description>TRUE</description>
    ///     </item>
    ///   </list>
    /// </remarks>
    public enum DebugOutput {
        /// <summary>
        /// Create no debug information.
        /// </summary>
        @false = 0,

        /// <summary>
        /// Create no debug information.
        /// </summary>
        None = @false,

        /// <summary>
        /// Enable attaching a debugger to the running program.
        /// </summary>
        @true = 1,

        /// <summary>
        /// Enable attaching a debugger to the running program.
        /// </summary>
        Full = @true,

        /// <summary>
        /// Only display assembler when the running program is attached to the 
        /// debugger.
        /// </summary>
        PdbOnly = 2
    }
}
