
language: c

install:
  - curl -sLo /tmp/mono.gpg http://download.mono-project.com/repo/xamarin.gpg
  - sudo apt-key add /tmp/mono.gpg
  - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy main' >> /etc/apt/sources.list.d/mono-xamarin.list"
  - sudo apt-get update -qq
  - sudo apt-get install -qq mono-devel mono-vbnc nuget libgdiplus=2.10-3

env:
  - TARGET=mono-2.0 MCS="mcs -sdk:2"
  - TARGET=mono-4.0 MCS="mcs -sdk:4"

script:
  - mono --version
  - make clean run-test TARGET=$TARGET MCS="$MCS"
    