using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("NAnt")]
[assembly: AssemblyDescriptionAttribute("A .NET Build Tool")]
[assembly: AssemblyConfigurationAttribute("alpha1")]
[assembly: AssemblyCompanyAttribute("http://nant.sourceforge.net")]
[assembly: AssemblyProductAttribute("NAnt")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2001-2010 Gerry Shaw")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("0.91.3801.0")]
[assembly: AssemblyInformationalVersionAttribute("0.91")]

